name: MobEscape
main: com.comze_instancelabs.mobescape.Main
version: 1.3.3
author: instancelabs
softdepend: [Vault]
commands:
   dragonescape:
      description: Main command
      usage: /dragonescape <action>
      aliases: [de]
   escapethemob:
      description: Main command
      usage: /escapethemob <action>
      aliases: [etm]
